name: Test
on:
  push:
    branches: [devop, main]

jobs:
  build:
    name: pytest tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
      name: Install python
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      name: Install deps
    - run: |
        python - m pip install --upgrade pip
        pip install -r requirements.txt
      name: Run flake8
    - run: flake8 .
      name: Test with pytest
    - run: |
        pytest