name: Test
on: [push]
jobs:
  tests:
    name: pytest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          args: pip install -r requirements.txt && python -m pytest tests/test_app.py